---
# tasks file for nignu-common
- name: install Variables for distributions
  include_vars: "os_{{ ansible_distribution }}.yml"

- name: include when Ubuntu
  include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include when Debian
  include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- name: include when Fedora
  include_tasks: 
    file: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- name: include when Archlinux
  include_tasks: "setup-ArchLinux.yml"
  when: ansible_os_family == 'Archlinux'

- name: create update-motd.d folder
  file:
    path: /etc/update-motd.d
    state: directory
  when: ansible_os_family == "Debian"

- name: remove motd file
  file:
    path: /etc/motd
    state: absent
  when: ansible_os_family == "Debian"

- name: Ensure Ensure /etc/update-motd/20-logo exists
  copy:
    src: files/etc/motd/20-logo
    dest: /etc/update-motd.d/20-logo
    owner: root
    group: root
    mode: '0550'
  when: ansible_os_family == "Debian"

- name: "set timezone"
  timezone:
    name: "{{ sys_timezone }}"
  when: sys_timezone is defined

- name: Ensure sshd_config file
  copy:
    src: files/etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart_sshd

#- name: Ensure logrotate service file
#  template:
#    src: templates/newitem.j2
#    dest: "/home/{{ user_name }}/{{ item.name }}.txt"
#    #    owner: root
#    #    group: "{{ root_group }}"
#    #    mode: '0644'
#  with_items:
#    - "{{ services }}"

#- name: ensure logrotate is started
#  systemd:
#    name: logrotate.service
#    state: started
#    enabled: yes

...
