---
- name: include vars "{{ ansible_facts['distribution'] }}"
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install archlinux packages
  pacman:
    name: "{{ packages_arch }}"
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: remove no longer required Archlinux packages
  pacman:
    name: "{{ remove_packages_arch }}"
    state: absent
  when: ansible_facts['distribution'] == 'Archlinux'
