---
- name: include vars for CentOS
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install centos distribution specific base packages
  yum:
    name: "{{ item}}"
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'CentOS'
  loop:
    - "{{ packages_centos }}"

- name: install CentOS packages
  apt:
    name: "{{ packages_centos }}"
    state: present
  when: ansible_facts['distribution'] == 'CentOS'

- name: remove no longer required CentOS packages
  apt:
    name: "{{ remove_packages_centos }}"
    state: absent
  when: ansible_facts['distribution'] == 'CentOS'
