---
- name: include vars for Debian
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] == 'Debian'
  
- name: install debian packages
  apt:
    name: "{{ packages_install }}"
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Debian'

- name: remove no longer needed debian packages
  apt:
    name: "{{ packages_remove }}"
    state: present
  when: packages_remove_debian == true

- name: Ensure ssh service is started and enabled
  systemd:
    enabled: yes
    daemon_reload: yes
    name: ssh
  when: ansible_facts['os_family'] == "Debian"
