---
- name: include vars for Ubuntu                        
  include_vars: "{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install Ubuntu packages
  apt:
    name: "{{ packages_install }}"
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: remove no longer required Ubuntu packages
  apt:
    name: "{{ packages_remove }}"
    state: absent
  when: packages_remove_ubuntu == true

- name: Ensure ssh service is started and enabled
  systemd:
    enabled: yes
    daemon_reload: yes 
    name: ssh
  when: ansible_facts['os_family'] == "Debian"
