---
- name: install archlinux packages
  pacman:
    name: "{{ __packages_install }}"
    state: present

- name: remove no longer required Archlinux packages
  pacman:
    name: "{{ packages_remove }}"
    state: absent
  when: packages_remove_archlinux == true

#    
#
# TODO
# https://github.com/pigmonkey/spark
#
# install and configure awesome WM
# for more  docs check
# https://wiki.archlinux.org/index.php/Awesome
#
#    $mkdir -p ~/.config/awesome
#    $cp /etc/xdg/awesome/rc.lua ~/.config/awesome/
#
#    also need to install vicious 
# clone git repo and change themes and configurations
# https://github.com/copycat-killer/awesome-copycats