---
- name: Install centos distribution specific base packages
  yum:
    name: "{{ item}}"
    state: present
    update_cache: true
  loop:
    - "{{ packages_centos }}"

- name: install RedHat family packages
  apt:
    name: "{{ packages_redhat }}"
    state: present

- name: remove no longer required CentOS packages
  apt:
    name: "{{ packages_remove }}"
    state: absent
  when: packages_remove_redhat == true

#    
#
# TODO
# https://github.com/pigmonkey/spark
#
# install and configure awesome WM
# for more  docs check
# https://wiki.archlinux.org/index.php/Awesome
#
#    $mkdir -p ~/.config/awesome
#    $cp /etc/xdg/awesome/rc.lua ~/.config/awesome/
#
#    also need to install vicious 
# clone git repo and change themes and configurations
# https://github.com/copycat-killer/awesome-copycats