#!/bin/sh
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 2)

                      .....                            |
                    ./+//::-                           |
                   .//++++//-                .         |
                   ///+++++++.              .:         |
                  -://+//ooo+o             -:-         |
                 .:////. /+o+s/         .:/:-          |
                ./////-  .//+oo:    .-/+o+/..-         |
                :////:    -////+-:/+oooo/--//.         |   `uname -srmo`$(tput setaf 1)
               :////:     '-//////++++/:/++:.          |   `uname -snrvm`
              -///++.     -:////+ossoo++/:-            |   Uptime.............: ${UPTIME}
             -+++oo:   ./+++/+osssssoo+++/.            |   Memory.............: `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
            .syyys/  ./ooosysssssssso+/:.              |   Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
            +yyyys. /oosssoo+//++++/.                  |   Running Processes..: `ps ax | wc -l | tr -d " "`
           /yyyyy-.++:-.      .oooooo                  |   IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/` and `wget -q -O - http://icanhazip.com/ | tail`
          -sssss: -.           -ooooy/                 |   Weather............: `curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|UK|UK001|NAILSEA|" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`
         oyyyys.                 /oosso.               |   Webpage............: `printf " * Documentation:  https://www.andorigna.com\n"`
         ......                   .....                |
                                                       |
                   _            _                      |
    __ _ _ __   __| | ___  _ __(_) __ _ _ __   __ _    |
   / _  | '_ \ / _  |/ _ \| '__| |/ _  | '_ \ / _  |   |
  | (_| | | | | (_| | (_) | |  | | (_| | | | | (_| |   |
   \__,_|_| |_|\__,_|\___/|_|  |_|\__, |_| |_|\__,_|   |
                                |___/                  |
				                                               |
							                                         |
`echo "\n"`                                               
`echo "\n"`                                               

$(tput sgr0)"
